Untabify, fix whitespace and indentation

diff --git a/git-sync b/git-sync
--- a/git-sync
+++ b/git-sync
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 #
 # git-sync
 #
@@ -90,56 +91,56 @@ __log_msg()
 # echo the git dir
 __gitdir()
 {
-	if [ "true" = "$(git rev-parse --is-inside-work-tree "$PWD" | head -1)" ]; then
-		git rev-parse --git-dir "$PWD" 2>/dev/null
-	fi
+    if [ "true" = "$(git rev-parse --is-inside-work-tree "$PWD" | head -1)" ]; then
+        git rev-parse --git-dir "$PWD" 2>/dev/null
+    fi
 }
 
 # echos repo state
 git_repo_state ()
 {
-	local g="$(__gitdir)"
-	if [ -n "$g" ]; then
-		if [ -f "$g/rebase-merge/interactive" ]; then
-			echo "REBASE-i"
-		elif [ -d "$g/rebase-merge" ]; then
-			echo "REBASE-m"
-		else
-			if [ -d "$g/rebase-apply" ]; then
-				echo "AM/REBASE"
-			elif [ -f "$g/MERGE_HEAD" ]; then
-				echo "MERGING"
-			elif [ -f "$g/CHERRY_PICK_HEAD" ]; then
-				echo "CHERRY-PICKING"
-			elif [ -f "$g/BISECT_LOG" ]; then
-				echo "BISECTING"
-			fi
-		fi
-		if [ "true" = "$(git rev-parse --is-inside-git-dir 2>/dev/null)" ]; then
-			if [ "true" = "$(git rev-parse --is-bare-repository 2>/dev/null)" ]; then
-				echo "|BARE"
-			else
-				echo "|GIT_DIR"
-			fi
-		elif [ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
-			git diff --no-ext-diff --quiet --exit-code || echo "|DIRTY"
-#			if [ -n "${GIT_PS1_SHOWSTASHSTATE-}" ]; then
-#			        git rev-parse --verify refs/stash >/dev/null 2>&1 && s="$"
-#			fi
-#
-#			if [ -n "${GIT_PS1_SHOWUNTRACKEDFILES-}" ]; then
-#			   if [ -n "$(git ls-files --others --exclude-standard)" ]; then
-#			      u="%"
-#			   fi
-#			fi
-#
-#			if [ -n "${GIT_PS1_SHOWUPSTREAM-}" ]; then
-#				__git_ps1_show_upstream
-#			fi
-		fi
-	else
-	    echo "NOGIT"
-	fi
+    local g="$(__gitdir)"
+    if [ -n "$g" ]; then
+        if [ -f "$g/rebase-merge/interactive" ]; then
+            echo "REBASE-i"
+        elif [ -d "$g/rebase-merge" ]; then
+            echo "REBASE-m"
+        else
+            if [ -d "$g/rebase-apply" ]; then
+                echo "AM/REBASE"
+            elif [ -f "$g/MERGE_HEAD" ]; then
+                echo "MERGING"
+            elif [ -f "$g/CHERRY_PICK_HEAD" ]; then
+                echo "CHERRY-PICKING"
+            elif [ -f "$g/BISECT_LOG" ]; then
+                echo "BISECTING"
+            fi
+        fi
+        if [ "true" = "$(git rev-parse --is-inside-git-dir 2>/dev/null)" ]; then
+            if [ "true" = "$(git rev-parse --is-bare-repository 2>/dev/null)" ]; then
+                echo "|BARE"
+            else
+                echo "|GIT_DIR"
+            fi
+        elif [ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
+            git diff --no-ext-diff --quiet --exit-code || echo "|DIRTY"
+            #                       if [ -n "${GIT_PS1_SHOWSTASHSTATE-}" ]; then
+            #                               git rev-parse --verify refs/stash >/dev/null 2>&1 && s="$"
+            #                       fi
+            #
+            #                       if [ -n "${GIT_PS1_SHOWUNTRACKEDFILES-}" ]; then
+            #                          if [ -n "$(git ls-files --others --exclude-standard)" ]; then
+            #                             u="%"
+            #                          fi
+            #                       fi
+            #
+            #                       if [ -n "${GIT_PS1_SHOWUPSTREAM-}" ]; then
+            #                               __git_ps1_show_upstream
+            #                       fi
+        fi
+    else
+        echo "NOGIT"
+    fi
 }
 
 # check if we only have untouched, modified or (if configured) new files
@@ -147,15 +148,15 @@ check_initial_file_state()
 {
     local syncNew="$(git config --get --bool branch.$branch_name.syncNewFiles)"
     if [[ "true" == "$syncNew" || "true" == "$sync_new_files_anyway" ]]; then
-	# allow for new files
-	if [ ! -z "$(git status --porcelain | grep -E '^[^ \?][^M\?] *')" ]; then
-	    echo "NonNewOrModified"
-	fi
+        # allow for new files
+        if [ ! -z "$(git status --porcelain | grep -E '^[^ \?][^M\?] *')" ]; then
+            echo "NonNewOrModified"
+        fi
     else
-	# also bail on new files
-	if [ ! -z "$(git status --porcelain | grep -E '^[^ ][^M] *')" ]; then
-	    echo "NotOnlyModified"
-	fi
+        # also bail on new files
+        if [ ! -z "$(git status --porcelain | grep -E '^[^ ][^M] *')" ]; then
+            echo "NotOnlyModified"
+        fi
     fi
 }
 
@@ -164,7 +165,7 @@ check_initial_file_state()
 local_changes()
 {
     if [ ! -z "$(git status --porcelain | grep -E '^(\?\?|[MARC] |[ MARC][MD])*')" ]; then
-	echo "LocalChanges"
+        echo "LocalChanges"
     fi
 }
 
@@ -174,38 +175,38 @@ sync_state()
     local count="$(git rev-list --count --left-right $remote_name/$branch_name...HEAD)"
 
     case "$count" in
-	"") # no upstream
-	    echo "noUpstream"
-	    false
-	    ;;
-	"0	0")
-	    echo "equal"
-	    true 
-	    ;;
-	"0	"*)
-	    echo "ahead"
-	    true
-	    ;;
-	*"	0")
-	    echo "behind"
-	    true
-	    ;;
-	*)
-	    echo "diverged"
-	    true
-	    ;;
+        "") # no upstream
+            echo "noUpstream"
+            false
+            ;;
+        "0      0")
+            echo "equal"
+            true
+            ;;
+        "0      "*)
+            echo "ahead"
+            true
+            ;;
+        *"      0")
+            echo "behind"
+            true
+            ;;
+        *)
+            echo "diverged"
+            true
+            ;;
     esac
 }
 
 # exit, issue warning if not in sync
 exit_assuming_sync() {
     if [ "equal" == "$(sync_state)" ] ; then
-	__log_msg "In sync, all fine."
-	exit 0;
+        __log_msg "In sync, all fine."
+        exit 0;
     else
-	__log_msg "Synchronization FAILED! You should definitely check your repository carefully!"
-	__log_msg "(Possibly a transient network problem? Please try again in that case.)"
-	exit 3
+        __log_msg "Synchronization FAILED! You should definitely check your repository carefully!"
+        __log_msg "(Possibly a transient network problem? Please try again in that case.)"
+        exit 3
     fi
 }
 
@@ -249,7 +250,7 @@ if [ -z "$remote_name" ] ; then
     echo
     __log_msg "Please use"
     echo
-    __log_msg "  git branch --set-upstream-to=[remote_name]/$branch_name" 
+    __log_msg "  git branch --set-upstream-to=[remote_name]/$branch_name"
     echo
     __log_msg "replacing [remote_name] with the name of your remote, i.e. - origin"
     __log_msg "to set the remote tracking branch for git-sync to work"
@@ -304,19 +305,19 @@ fi
 if [ ! -z "$(local_changes)" ]; then
     autocommit_cmd=""
     config_autocommit_cmd="$(git config --get branch.$branch_name.autocommitscript)"
-    
+
     # discern the three ways to auto-commit
     if [ ! -z "$config_autocommit_cmd" ]; then
-	autocommit_cmd="$config_autocommit_cmd"
+        autocommit_cmd="$config_autocommit_cmd"
     elif [[ "true" == "$(git config --get --bool branch.$branch_name.syncNewFiles)" || "true" == "$sync_new_files_anyway" ]]; then
-	autocommit_cmd=${ALL_AUTOCOMMIT_CMD}
+        autocommit_cmd=${ALL_AUTOCOMMIT_CMD}
     else
         autocommit_cmd=${DEFAULT_AUTOCOMMIT_CMD}
     fi
 
     commit_msg="$(git config --get branch.$branch_name.syncCommitMsg)"
     if [ "" == "$commit_msg" ]; then
-      commit_msg=${DEFAULT_AUTOCOMMIT_MSG}
+        commit_msg=${DEFAULT_AUTOCOMMIT_MSG}
     fi
     autocommit_cmd=$(echo "$autocommit_cmd" | sed "s/%message/$commit_msg/")
 
@@ -326,8 +327,8 @@ if [ ! -z "$(local_changes)" ]; then
     # after autocommit, we should be clean
     rstate="$(git_repo_state)"
     if [[ ! -z "$rstate" ]]; then
-	__log_msg "Auto-commit left uncommitted changes. Please add or remove them as desired and retry."
-	exit 1
+        __log_msg "Auto-commit left uncommitted changes. Please add or remove them as desired and retry."
+        exit 1
     fi
 fi
 
@@ -341,45 +342,44 @@ if [ $? != 0 ] ; then
 fi
 
 case "$(sync_state)" in
-"noUpstream")
-	__log_msg "Strange state, you're on your own. Good luck."
-	exit 2
-	;;
-"equal")
-	exit_assuming_sync
-	;;
-"ahead")
-	__log_msg "Pushing changes..."
-	git push $remote_name $branch_name:$branch_name
-	if [ $? == 0 ]; then
-	    exit_assuming_sync
-	else
-	    __log_msg "git push returned non-zero. Likely a connection failure."
-	    exit 3
-	fi
-	;;
-"behind")
-	__log_msg "We are behind, fast-forwarding..."
-	git merge --ff --ff-only $remote_name/$branch_name
-	if [ $? == 0 ]; then
-	    exit_assuming_sync
-	else
-	    __log_msg "git merge --ff --ff-only returned non-zero ($?). Exiting."
-	    exit 2
-	fi
-	;;
-"diverged")
-	__log_msg "We have diverged. Trying to rebase..."
-	git rebase $remote_name/$branch_name
-	if [[ $? == 0 && -z "$(git_repo_state)" && "ahead" == "$(sync_state)" ]] ; then
-	    __log_msg "Rebasing went fine, pushing..."
-	    git push $remote_name $branch_name:$branch_name
-	    exit_assuming_sync
-	else
-	    __log_msg "Rebasing failed, likely there are conflicting changes. Resolve them and finish the rebase before repeating git-sync."
-	    exit 1
-	fi
-	# TODO: save master, if rebasing fails, make a branch of old master
-	;;
+    "noUpstream")
+        __log_msg "Strange state, you're on your own. Good luck."
+        exit 2
+        ;;
+    "equal")
+        exit_assuming_sync
+        ;;
+    "ahead")
+        __log_msg "Pushing changes..."
+        git push $remote_name $branch_name:$branch_name
+        if [ $? == 0 ]; then
+            exit_assuming_sync
+        else
+            __log_msg "git push returned non-zero. Likely a connection failure."
+            exit 3
+        fi
+        ;;
+    "behind")
+        __log_msg "We are behind, fast-forwarding..."
+        git merge --ff --ff-only $remote_name/$branch_name
+        if [ $? == 0 ]; then
+            exit_assuming_sync
+        else
+            __log_msg "git merge --ff --ff-only returned non-zero ($?). Exiting."
+            exit 2
+        fi
+        ;;
+    "diverged")
+        __log_msg "We have diverged. Trying to rebase..."
+        git rebase $remote_name/$branch_name
+        if [[ $? == 0 && -z "$(git_repo_state)" && "ahead" == "$(sync_state)" ]] ; then
+            __log_msg "Rebasing went fine, pushing..."
+            git push $remote_name $branch_name:$branch_name
+            exit_assuming_sync
+        else
+            __log_msg "Rebasing failed, likely there are conflicting changes. Resolve them and finish the rebase before repeating git-sync."
+            exit 1
+        fi
+        # TODO: save master, if rebasing fails, make a branch of old master
+        ;;
 esac
-
